### ISSUE TITLE
Error: no such table: default__LEDGER__

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1643]
We got errors during the event store import:
      Event listener "Comments" can't resume subscription since event bus
      cannot initiate notification for it because of error "Error: SQLITE_ERROR: no such table: default__LEDGER__"

**Comment by IhostVlad** [comment]
Context: error appears only in importing event mode (first-run non-incremental import). Not related with dev, cloud or other modes, in which read-models are really used

**Comment by IhostVlad** [comment]
Fixed in 0.26.1

**Comment by arubtsov** [comment]
The problem still stands on 0.26.3:

_[internal build log link removed by maintainer]_

**Comment by MrCheater** [comment]
Fixed in 0.28.2
